language: node_js
dist: trusty
sudo: required
node_js: 6
script:
- npm run test

cache:
  directories:
  - node_modules
env:
  global:
  - CF_APP=natural-language-understanding-demo
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
before_deploy: npm install -g https://github.com/germanattanasio/cf-blue-green
deploy:
  skip_cleanup: true
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/natural-language-understanding-nodejs
notifications:
  email: false
